-- La tabla Usuario y rol estan faltando.

/***
  TABLA JUZGADO
 */
-- Tabla JUZGADO

CREATE TABLE SOPORTE.juzgado
(
    ID_JUZGADO        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- Auto-incremental
    NOMBRE            VARCHAR2(100) NOT NULL,
    LUGAR             VARCHAR2(250),
    ESTADO            NUMBER(1) DEFAULT 1 CHECK (ESTADO IN (0, 1)),
    FECHA_CREACION    DATE,
    FECHA_ACTUALIZADA DATE,
    CREADO_POR        varchar2(100),
    ACTUALIZADO_POR   varchar2(100)
    -- Booleano: 1 (activo), 0 (inactivo)
);
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('9º Juzgado Civil', 1, SYSDATE, 'Lima');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('1er Juzgado Mixto de Carabayllo', 1, SYSDATE, 'Carabayllo');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('1º Juzgado Civil de Piura', 1, SYSDATE, 'Piura');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('1º Juzgado de Paz Letrado de Jacobo Hunter', 1, SYSDATE, 'Arequipa');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('5º Juzgado Civil de Lima', 1, SYSDATE, 'Lima');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('2º Juzgado Civil de Lima', 1, SYSDATE, 'Lima');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('Juzgado Civil Transitorio de Villa El Salvador', 1, SYSDATE, 'Villa El Salvador');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('8º Juzgado Civil de Arequipa', 1, SYSDATE, 'Arequipa');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('4º Juzgado Mixto de SJL', 1, SYSDATE, 'San Juan de Lurigancho');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('2º Juzgado Civil Transitorio de Trujillo', 1, SYSDATE, 'Trujillo');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('12º Juzgado Civil de Lima', 1, SYSDATE, 'Lima');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('15º Juzgado Contencioso Administrativo Permanente de Lima', 1, SYSDATE, 'Lima');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('3º Juzgado Civil de Tacna', 1, SYSDATE, 'Tacna');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('1º Juzgado Civil de Villa El Salvador', 1, SYSDATE, 'Villa El Salvador');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('1º Juzgado Civil de Ica', 1, SYSDATE, 'Ica');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('6º Juzgado Civil de Trujillo', 1, SYSDATE, 'Trujillo');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('Juzgado Civil de Villa El Salvador', 1, SYSDATE, 'Villa El Salvador');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('5º Juzgado Civil de Piura', 1, SYSDATE, 'Piura');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('3º Juzgado de Trabajo de Arequipa', 1, SYSDATE, 'Arequipa');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('3º Juzgado Contencioso Administrativo de Lima', 1, SYSDATE, 'Lima');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('Juzgado Civil MBJ de Los Olivos', 1, SYSDATE, 'Los Olivos');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('2º Juzgado Civil de Arequipa', 1, SYSDATE, 'Arequipa');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('1º Juzgado Civil Transitorio de Lima Sur', 1, SYSDATE, 'Lima Sur');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('2º Juzgado Civil de Ayacucho', 1, SYSDATE, 'Ayacucho');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('1º Juzgado Civil de Lima', 1, SYSDATE, 'Lima');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('1º Juzgado Civil de Villa El Salvador', 1, SYSDATE, 'Villa El Salvador');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('2º Juzgado Civil de Tacna', 1, SYSDATE, 'Tacna');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('14º Juzgado Contencioso Administrativo de Lima', 1, SYSDATE, 'Lima');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('1º Juzgado Civil de Talara', 1, SYSDATE, 'Talara');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('1º Juzgado Transitorio de Trabajo de Huaura', 1, SYSDATE, 'Huaura');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('2º Juzgado Contencioso Administrativo de Lima', 1, SYSDATE, 'Lima');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('12º Juzgado Contencioso Administrativo de Lima', 1, SYSDATE, 'Lima');
INSERT INTO soporte.Juzgado (nombre, estado, fecha_creacion, lugar)
VALUES ('9º Juzgado Contencioso Administrativo de Lima', 1, SYSDATE, 'Lima');

/**
  TABLA ETAPA PROCESAL
 */
-- Tabla Etapa Procesal

CREATE TABLE SOPORTE.etapa_procesal
(
    ID_ETAPA          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- Auto-incremental
    NOMBRE            VARCHAR2(100) NOT NULL,
    ESTADO            NUMBER(1) DEFAULT 1 CHECK (ESTADO IN (0, 1)),
    FECHA_CREACION    date,
    FECHA_ACTUALIZADA date,
    CREADO_POR        varchar2(100),
    ACTUALIZADO_POR   varchar2(100)
); -- Booleano: 1 (activo), 0 (inactivo)
INSERT INTO SOPORTE.Etapa_Procesal (NOMBRE, ESTADO, FECHA_CREACION)
VALUES ('TRÁMITE', 1, SYSDATE);
INSERT INTO SOPORTE.Etapa_Procesal (NOMBRE, ESTADO, FECHA_CREACION)
VALUES ('PRIMERA INSTANCIA', 1, SYSDATE);
INSERT INTO SOPORTE.Etapa_Procesal (NOMBRE, ESTADO, FECHA_CREACION)
VALUES ('SEGUNDA INSTANCIA', 1, SYSDATE);
INSERT INTO SOPORTE.Etapa_Procesal (NOMBRE, ESTADO, FECHA_CREACION)
VALUES ('EJECUCIÓN', 1, SYSDATE);
INSERT INTO SOPORTE.Etapa_Procesal (NOMBRE, ESTADO, FECHA_CREACION)
VALUES ('ARCHIVO', 1, SYSDATE);

-- Tabla Tipo de Contingencia
CREATE TABLE SOPORTE.tipo_contingencia
(
    ID_CONTINGENCIA   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- Auto-incremental
    NOMBRE            VARCHAR2(100) NOT NULL,
    ESTADO            NUMBER(1) DEFAULT 1 CHECK (ESTADO IN (0, 1)),
    FECHA_CREACION    date,
    FECHA_ACTUALIZADA date,
    CREADO_POR        varchar2(100),
    ACTUALIZADO_POR   varchar2(100)
    -- Booleano: 1 (activo), 0 (inactivo)
);
INSERT INTO SOPORTE.tipo_contingencia (NOMBRE, ESTADO, FECHA_CREACION)
VALUES ('PROBABLE', 1, sysdate);
INSERT INTO SOPORTE.tipo_contingencia (NOMBRE, ESTADO, FECHA_CREACION)
VALUES ('PRESENTE', 1, sysdate);
INSERT INTO SOPORTE.tipo_contingencia (NOMBRE, ESTADO, FECHA_CREACION)
VALUES ('CONCLUIDO', 1, sysdate);
INSERT INTO SOPORTE.tipo_contingencia (NOMBRE, ESTADO, FECHA_CREACION)
VALUES ('REMOTO', 1, sysdate);

CREATE TABLE SOPORTE.proceso_judiciales
(
    ID_PROCESO_JUDICIAL NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_JUZGADO          NUMBER,                                                     -- Foreign key hacia Juzgado
    n_expediente        VARCHAR2(150), -- AUTO-INCREMENTAL
    MATERIA             VARCHAR2(255),
    MONTO               NUMBER(15, 2),
    TIPO_MONEDA         VARCHAR2(10),
    DEMANDANTE          VARCHAR2(100),
    DEMANDADO           VARCHAR2(100),
    ABOGADO             VARCHAR2(255),
    FECHA_CREACION      DATE,
    FECHA_ACTUALIZADA   DATE,
    CREADO_POR          VARCHAR2(100),
    ACTUALIZADO_POR     VARCHAR2(100),
    CONSTRAINT FK_JUZGADO FOREIGN KEY (ID_JUZGADO) REFERENCES Juzgado (ID_JUZGADO)
);

CREATE TABLE SOPORTE.uap_movimiento
(
    ID_MOVIMIENTO       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_PROCESO_JUDICIAL NUMBER,                                                     -- Foreign key hacia proceso_judiciales-- Auto-incremental
    NOMBRE              VARCHAR2(100) NOT NULL,
    ID_ETAPA            NUMBER,
    ID_CONTINGENCIA     NUMBER,                                                     -- Foreign key hacia Tipo de Contingencia
    FECHA_CREACION      date,
    FECHA_ACTUALIZADA   date,
    CREADO_POR          varchar2(100),
    ACTUALIZADO_POR     varchar2(100),
    CONSTRAINT FK_EXPEDIENTE FOREIGN KEY (id_proceso_judicial) REFERENCES proceso_judiciales (id_proceso_judicial),
    CONSTRAINT FK_ETAPA FOREIGN KEY (ID_ETAPA) REFERENCES Etapa_Procesal (ID_ETAPA),-- Booleano: 1 (activo), 0 (inactivo)
    CONSTRAINT FK_CONTINGENCIA FOREIGN KEY (ID_CONTINGENCIA) REFERENCES Tipo_Contingencia (ID_CONTINGENCIA)
);